### ISSUE TITLE
execArgs is being passed incorrectly

### ISSUE THREAD

**Issue by Deilan** [remy/nodemon#1250] opened 2018-02-08 10:01 UTC
- `nodemon -v`: 1.14.12
- `node -v`: 8.9.4
- Operating system/terminal environment: Windows 10 x64
- Command you ran:

`nodemon` with the following `nodemon.json`:
```json
{
    "verbose": true,
    "watch": [
        "src"
    ],
    "ext": "ts",
    "execArgs": ["--inspect=5858"],
    "exec": "{{pwd}}/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json"
}
```
### Expected behaviour
`--inspect=5858` passed as an argument of `node`

### Actual behaviour
`--inspect=5858` passed as an argument of `ts-node`

terminal output:
```
[nodemon] 1.14.12
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 22156 to restart
[nodemon] watching: C:\Dev\node-typescript-vscode\src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `C:\Dev\node-typescript-vscode/node_modules/.bin/ts-node ./src/index.ts --project ./tsconfig.development.json --inspect=5858`
[nodemon] spawning
[nodemon] child pid: 11272
[nodemon] watching 2 files
```

### Steps to reproduce
1. clone https://github.com/Deilan/nodemon-issue-1250
2. `yarn install` or `npm install`
3. `yarn run serve:debug` or `npm run serve:debug`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Deilan** [comment] 2018-02-08 10:05
If it's by design then how to pass arguments before `exec`, so they arrive as `node` arguments and not `ts-node`?

**Comment by remy** [comment] 2018-02-08 10:35
Shouldn't `ts-node` pass node argmenents along to node that it doesn't recognise? (The same way nodemon does)

**Comment by remy** [comment] 2018-02-08 11:33
I'm going to close this as it's not a bug or anything I can do anything about. Specifically to understand, since you (the user) is telling nodemon to execute your script using `ts-node` nodemon has no idea that node is in the stack of execution anywhere. You might as well be running `grep` from nodemon's point of view.

So being able to pass arguments to node because you're running `ts-node` isn't at all possible since nodemon never sees or knows that node is part of the execution pipeline (in fact, it's your OS that decides to run node in `ts-node`: https://github.com/TypeStrong/ts-node/blob/d5a941cf7f03f8a2b7cd2c761efe5dba4c75cba6/src/bin.ts#L1 - so your OS could run thoretically anything).

I do strongly recommend raising a bug against `ts-node` requesting that the pass any unknown arguments along to node so that you _can_ do things like inspection. But as for nodemon, it's nothing I can change to help.

**Closed by remy** 2018-02-08 11:33 UTC
