### ISSUE TITLE
Starting unexisting (yet) script fails

### ISSUE THREAD

**Issue by DGolubets** [remy/nodemon#1310] opened 2018-04-08 15:25 UTC
- `nodemon -v`: 1.17.3
- `node -v`: 8.9.3
- Operating system/terminal environment: Windows 10/powershell
- Command you ran: nodemon target/build/main/server.js

### Expected behaviour
It should fail to find the file, then eventually pick it up and restart.

### Actual behaviour
It starts watching "main" script from package.json or fails if there is none.

### Steps to reproduce
Should be always reproducible

### More info
*nodemon/lib/cli/parse* looks for script name by iterating over arguments and checking if file exists.
It would be nice to have dedicated parameter for script, e.g. ```nodemon --script ./build/server.js```

**Comment by remy** [comment] 2018-04-09 06:58
Dupe of #1297. This is really a feature request and I'd consider a PR for it.

**Closed by remy** 2018-04-09 06:58 UTC
