### ISSUE TITLE
-r option does not load properly

### ISSUE THREAD

**Issue by azopyros** [remy/nodemon#1163] opened 2017-12-14 13:08 UTC
- `nodemon -v`: 1.12.6
- `node -v`: v6.9.1
- Command you ran: npm run dev

Hello,
First, here is an extract from my package.json:
```javascript
"scripts": {
    "start": "node -r dotenv-extended/config index.js",
    "dev": "nodemon -r dotenv-extended/config index.js"
}
```
`doten-extended/config` override my `process.env` to add some value I store on my `.env` file.

What append :
```bash
> npm run dev
# process.env.FOO === undefined

> npm run start
# process.env.FOO === BAR

> nodemon@1.11.0 -r dotenv-extended/config index.js
# process.env.FOO === BAR
```
`-r` options seems to works with `nodemon@1.11.0`

Is it something you experienced ? Did I pass some variable wrong ?

Thanks :)

**Comment by remy** [comment] 2017-12-14 17:28
Can't replicate. This is the code I'm using (based on the information provided): https://gist.github.com/remy/968b8937a153127cfae4a173b6000c1e

Then execution:

<img width="758" alt="screen shot 2017-12-14 at 17 27 31" src="https://user-images.githubusercontent.com/13700/34005833-164c8d74-e0f4-11e7-97d6-5ddc9ba7e926.png">

I'm on nodemon@1.12.7 - not sure if that is the key difference?

**Comment by dominykas** [comment] 2017-12-18 14:44
I was able to reproduce with nodemon@1.12.6 - it seems to work with latest nodemon (1.13.3).

**Comment by remy** [comment] 2017-12-20 12:54
Acknowledge. I'm able to replicate with 1.12.6, but since fixed in latest. Thanks for confirmation @dominykas 👍

**Closed by remy** 2017-12-20 12:54 UTC
Labels: can't replicate
