### ISSUE TITLE
`sh` escaping of exec command is buggy

### ISSUE THREAD

**Issue by gfxmonk** [remy/nodemon#444] opened 2014-12-19 06:49 UTC
I noticed https://github.com/remy/nodemon/commit/f7537533dd55251c029b4774e3b70d12f75ecbff, which seems to be without tests?

Escaping only `"` characters is not enough - e.g an exec string of `bin/some\\"file` will cause a parse error in `sh`.

Also metacharacters inside single quotes will be incorrectly interpreted, e.g `\'bin/some`date`\'` will dutifully try and run `bin/someFri 19 Dec 17:46:59 AEDT 2014` even though it's inside (escaped) single quotes.

While I'm at it, passing in `bin/some\ \'file` drops that escaped single quote, for possibly-unrelated reasons.

The fix might be better escaping, but personally I'd reconsider the feature in the first place. Getting escaping wrong (when it comes to shell commands) can cause pretty severe bugs when data is accidentally interpreted as a command.

**Comment by remy** [comment] 2015-01-08 10:30
I've been sucked into a few other issues, but would you try the latest nodemon@dev version with your examples? I've got some tests in place that cover these issues (and fixes that handle the escapes in the exec etc). I'm secretly hoping that they're all fixed in the change I made, but I honestly suspect they're not! :)

**Comment by gfxmonk** [comment] 2015-01-08 23:09
OK, testing on 86baf99ee2f408165f68a1a7af1cc0319bc5a1fd

(note: I don't actually have scripts by these names atm, but the error message implies it's now _trying_ to run the right thing)

$ ./bin/nodemon.js -x 'bin/some\\\"file'
sh: bin/some\"file: No such file or directory

:thumbsup:

$ ./bin/nodemon.js -x 'bin/some\ '\''file'
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file

:thumbsup:

But this is still broken, in two different ways:

$ ./bin/nodemon.js -x "\'bin/some\`date\`\'"
sh: 'bin/someFri: No such file or directory

 - it should not execute `date`, since it's within single quotes
 - after accidentally executing `date`, it's _also_ splitting the result on spaces (i.e it tries to execute `bin/someFri`, not `bin/someFri  9 Jan 09:58:13 AEDT 2015`)

----

Also, I didn't check this before, but I've also noticed that, _all additional arguments_ (even those not passed to exec) now need to be double-escaped. e.g to pass the argument "foo bar baz" through, you have to quote it (for bash) and then escape it (for nodemon):

$ ./bin/nodemon.js -x 'ls' -- 'foo bar baz' # splits argument on spaces
ls: cannot access foo: No such file or directory
ls: cannot access bar: No such file or directory
ls: cannot access baz: No such file or directory

$ ./bin/nodemon.js -x 'ls' -- 'foo\ bar\ baz' # double-escaped
ls: cannot access foo bar baz: No such file or directory

This one seems like a straight-up bug - i.e while there is _some_ reason to require arguments to `--exec` to be escaped (even if I don't agree with it :P), I don't think there's any conceivable reason to require escaping of additional args like this.

**Comment by remy** [comment] 2015-01-09 13:17
I'll give the backtick thing a look, but your last point, yeah, that's definitely a bug. I'll fix that.

**Comment by remy** [comment] 2015-01-09 21:12
Right, the last point is actually a bug in nodemon 1.2.1 - i.e. it's not a regression. That puts me on the fence whether to try to fix it (because this double escaping thing is hell to work with)...

**Comment by remy** [comment] 2015-01-21 10:44
Nodemon 1.3 is all live now with new tests for escaping and spaces. Thanks for the feedback.

**Closed by remy** 2015-01-21 10:44 UTC
Labels: needs more info
