### ISSUE TITLE
Segmentation fault: 11 error

### ISSUE THREAD

**Issue by iamwave007** [remy/nodemon#632] opened 2015-09-15 03:44 UTC
I installed the newest version1.5.0  and it's giving me this when i run it..

**Comment by remy** [comment] 2015-09-15 06:08
Dupe of #630 - I'm closing, please read the thread and add all the information you can to help diagnose.

**Closed by remy** 2015-09-15 06:08 UTC

**Comment by iamwave007** [comment] 2015-09-15 07:58
Thanks it's working!

**Comment by remy** [comment] 2015-09-15 08:08
What changed?

**Comment by iamwave007** [comment] 2015-09-15 08:30
i don't really know, i re-installed nodemon; the first time i installed it, internet might have been interrupted.
