### ISSUE TITLE
nodemon 1.17.2 not working, 1.17.1 ok

### ISSUE THREAD

**Issue by darky** [remy/nodemon#1294] opened 2018-03-15 10:26 UTC
- `nodemon -v`: 1.17.2
- `node -v`: 9.8.0
- Operating system/terminal environment: Arch
- Command you ran: nodemon -e ts,js,tsx,jsx,jade --inspect=9229 ./bin/www

### Expected behaviour
It working

### Actual behaviour
Not working

### Steps to reproduce
Simply try, maybe it only on Arch linux

**Comment by MattSidor** [comment] 2018-03-21 00:03
Can you give us any more information other than "not working"? For example, what symptoms do you observe that indicate it is not working? Are there any error messages?

**Comment by darky** [comment] 2018-03-21 10:05
Not working restart via watching files. No error messages

**Comment by gavinaiken** [comment] 2018-03-22 20:33
Experiencing the same. nodemon process seems to go to 100% and doesn't restart after a file change, or sometimes does but only after an extremely long delay. (On OSX, node 8.9.4, nodemon 1.17.2). Reverting to 1.17.1 fixes the issue.

**Comment by remy** [comment] 2018-03-24 08:56
@gavinaiken are you working with typescript too or is this a simple hello world script ala `require('http').createServer((req, res) => res.end('ok')).listen(8000)`?

**Comment by gavinaiken** [comment] 2018-03-24 15:34
No, not working with typescript, just javascript. I'm using `gulp-nodemon` with a gulp task to re-run mocha tests. I've been using the same setup for a couple of years, it has always worked well until this version of nodemon. Here's the gulp task:

```
gulp.task('mocha-tdd', false, ['test-pre', 'build-modules'], function (cb) {
    var exec = 'gulp mocha';

    return nodemon({
        watch: [ paths.moduleSrc, paths.testSrc ],
        ignore: [ paths.web, paths.build ],
        ext: 'js json yml',
        exec: exec
    });
});
```

It's watching a couple of thousand files, we have quite a big project across a bunch of modules.

**Comment by remy** [comment] 2018-03-31 06:48
Can you replicate with nodemon directly (by removing the nodemon-gulp?) Just to rule it out?

**Comment by remy** [comment] 2018-03-31 07:58
Also, I doubt if it's related, but I've released a small bug fix at 1.17.3

**Comment by darky** [comment] 2018-04-02 10:28
On 1.17.3 I have this blocker https://github.com/remy/nodemon/issues/1305

**Comment by gavinaiken** [comment] 2018-04-03 17:31
Yes I can reproduce it with just the nodemon command, along these lines:
```
node_modules/.bin/nodemon -w '../[a-zA-Z]*}/src/**/*.js' -w '../[a-zA-Z]*}/test/**/*.js' -i ../web-client -e js,json,yml -x 'gulp mocha'
```

I see the problem (using the above command) with 1.17.2 and 1.17.3 but not with 1.17.1

**Comment by gavinaiken** [comment] 2018-04-03 18:05
Trying to narrow down what change has caused the problem. Comparing versions https://github.com/remy/nodemon/compare/v1.17.1...v1.17.2 it seems most of the changes are in `lib/monitor/watch.js`, and if I copy that file from 1.17.1 and use it with 1.17.2 I do not observe the problem. So it's definitely one of the changes in there.

**Comment by gavinaiken** [comment] 2018-04-03 19:24
Starting to get to the bottom of the issue. Looks like we have been using `nodemon` incorrectly for a long time, but it was working anyway, although not doing exactly what we thought it was doing. The recent change has broken that behaviour.

In more detail - we have always passed a glob pattern as the watch argument. Reading the README I see that it says not to do that, but to pass directories instead. i.e. we have been doing it wrong...

Our glob pattern is quite complex but I can reproduce the issue just with a simple glob pattern eg

```
DEBUG=nodemon* nodemon -w '../[A-Za-z]*/src' -e js,json,yml -x 'gulp mocha'
```

If I run that, I see a debug output line like this:
```
  nodemon config: dirs [ '/Users/gavin/repos/node-core' ] +47ms
```
where `/Users/gavin/repos/node-core` is the absolute path equivalent of `../` - i.e. nodemon is just ignoring the `[A-Za-z]*/src` part of the glob pattern. Fair enough, the docs do say not to use globs!

The change in behaviour however seems to be that in 1.17.1 all the `node_modules` dirs under `/Users/gavin/repos/node-core` are ignored. (There are several of them, and lots of module dependencies.) In 1.17.2 and .3, it is watching files in the `node_modules` dirs. This is despite it outputting this debug:

```
  nodemon ignored [ '**/.git/**',
  '**/.nyc_output/**',
  '**/.sass-cache/**',
  '**/bower_components/**',
  '**/coverage/**',
  '**/node_modules/**',
```

which says it will be ignoring anything in those dirs. That seems to have been broken in 1.17.2.

So I need to expand my glob pattern before passing it in to nodemon as the watch args, which I think will resolve my issue, because I will then be watching subdirs with no `node_modules`. But it looks like there is a bug in the latest that needs resolving to make it honor the ignores properly.

**Comment by remy** [comment] 2018-04-04 08:12
I'm still trying to digest this detail, but for reference, the _main_ change in `watch.js` is this line:

```
cwd: process.cwd()
```

Which, as subtle as it looks, does have a fairly significant impact.

@gavinaiken are you able to replicate with a simpler project? I've got an issues repo that I test against which if I can replicate too, I should be able to fix (I've seen this similar issue in the past, and it's always down to the combination of watch/ignore and chokidar options).

**Comment by gavinaiken** [comment] 2018-04-05 11:54
Yes I just replicated with a very simple project. It seems that problem only shows up if you have nodemon watching a parent directory. We have a monorepo with lots of npm modules in a directory which is managed by git. With the glob problem I described above, we were watching the parent dir which contains all the modules (which is more or less what we want to do anyway), and when you do that it seems that nodemon 1.17.2 watches the contents of node_modules in all the other child dirs of the parent except the current dir. Here's a simple set of steps to demonstrate the issue:

```
mkdir nodemon-test
cd nodemon-test
mkdir nodemon-test-1.17.1
cd nodemon-test-1.17.1
touch index.js
npm init --yes
npm install nodemon@1.17.1

cd ..
mkdir nodemon-test-1.17.2
cd nodemon-test-1.17.2
touch index.js
npm init --yes
npm install nodemon@1.17.2

cd ../nodemon-test-1.17.1
DEBUG=nodemon* node_modules/.bin/nodemon -w .. --exec echo restart

cd ../nodemon-test-1.17.2
DEBUG=nodemon* node_modules/.bin/nodemon -w .. --exec echo restart
```

If you do those steps exactly you should see that the 1.17.1 outputs this debug:

```
  nodemon:watch watching dir: nodemon-test-1.17.1/package.json +0ms
  nodemon:watch watching dir: nodemon-test-1.17.1/index.js +0ms
  nodemon:watch watching dir: nodemon-test-1.17.2/index.js +1ms
  nodemon:watch watching dir: nodemon-test-1.17.2/package.json +0ms
```

whereas 1.17.2 outputs this:

```
  nodemon:watch watching dir: ../nodemon-test-1.17.1/index.js +0ms
  nodemon:watch watching dir: ../nodemon-test-1.17.1/package.json +0ms
  nodemon:watch watching dir: index.js +0ms
  nodemon:watch watching dir: package.json +0ms
  nodemon:watch watching dir: ../nodemon-test-1.17.1/node_modules/abbrev/LICENSE +55ms
... very many lines for node_modules ...
```

**Comment by gavinaiken** [comment] 2018-04-19 12:55
I don't think this issue should be closed - I replicated the issue with a very simple set of commands (see my previous comment) so this should be easy to reproduce, and seems to me to be worth fixing.

**Comment by remy** [comment] 2018-04-19 14:05
@gavinaiken +1 - I was trying to replicate this morning, but real/paid work took a priority. I'll try to take another look again to work out what the right fix is.

**Closed** 2018-05-05 19:17 UTC
Labels: bug, has PR

**Comment by gavinaiken** [comment] 2018-05-08 08:31
1.17.4 seems to work great to me, thanks for the fix! 👍
