### ISSUE TITLE
Infinite loop when starting nodemon

### ISSUE THREAD

**Issue by Impozible** [remy/nodemon#505] opened 2015-02-13 11:50 UTC
Hi everyone.

I'm trying to create a simple REST api with Node, Express, Swig and MongoDB, but when I try to start my app, it runs in an infinte loop tha goes like this:

```
$ npm start

> apirest-myproject@0.0.0 start /home/jfuertes/repositories/projects/myproject


> nodemon ./bin/www

13 Feb 12:42:27 - [nodemon] v1.3.7
13 Feb 12:42:27 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:42:27 - [nodemon] watching: *.*
13 Feb 12:42:27 - [nodemon] starting `nodemon ./bin/www ./bin/www`
13 Feb 12:42:28 - [nodemon] v1.3.7
13 Feb 12:42:28 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:42:28 - [nodemon] watching: *.*
13 Feb 12:42:28 - [nodemon] starting `nodemon ./bin/www ./bin/www ./bin/www`
13 Feb 12:42:28 - [nodemon] v1.3.7
13 Feb 12:42:28 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:42:28 - [nodemon] watching: *.*
13 Feb 12:42:28 - [nodemon] starting `nodemon ./bin/www ./bin/www ./bin/www ./bin/www`

```

And so on. Do you know what could be happening?

Here is my nodemon --dump

```
 $ nodemon --dump
13 Feb 12:50:13 - [nodemon] v1.3.7
13 Feb 12:50:13 - [nodemon] to restart at any time, enter `rs`
13 Feb 12:50:13 - [nodemon] watching: *.*
--------------
node: v0.13.0-pre
nodemon: v1.3.7
command: node /usr/local/bin/nodemon --dump
cwd: /home/jfuertes/repositories/projects/myproject
OS: linux x64
--------------
{ run: false,
  system: 
   { cwd: '/home/jfuertes/repositories/projects/myproject',
     useFind: false,
     useWatch: true,
     useWatchFile: false },
  required: false,
  dirs: [ '/home/jfuertes/repositories/projects/myproject' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: './bin/www',
        exec: 'nodemon',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!.git',
        '!/home/jfuertes/repositories/projects/myproject/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command: 
   { raw: { executable: 'nodemon', args: [ './bin/www' ] },
     string: 'nodemon ./bin/www' },
  offset: 0 }
--------------
```
Thank you so much in advance.

**Comment by LinusU** [comment] 2015-02-13 12:02
@Impozible please read up on [Fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that we can easier read your output. You'll want to edit your post with the output wrapped like this: (' should be `)

```text
'''text
text goes here...
'''
```

**Comment by Impozible** [comment] 2015-02-13 12:04
Ok, I just edited my message. Thank you for your fast answer.

**Comment by hai-cea** [comment] 2015-02-24 00:20
I'm experiencing this issue as well. Any ideas on why this is happening?

**Comment by remy** [comment] 2015-02-24 08:46
Can anyone else confirm this issue is happening on node 0.13? Or can you replicate on node stable too?

**Comment by remy** [comment] 2015-02-27 11:43
Ping @hai-cea - can you confirm the version of node you're running with?

**Comment by hai-cea** [comment] 2015-02-27 17:28
Hi @remy  - I'm using NVM - node v0.12.0

**Comment by Wenzil** [comment] 2015-05-12 02:50
Nodemon CPU usage goes through the roof whenever the `ignore` parameter is used. I suspect this is related. 

I'm on Node v0.12.2.

**Comment by cbankester** [comment] 2015-05-20 19:09
Having the same issue with node 0.12.2. Let me know if you'd like any more information; I'm very motivated to get this issue figured out.

**Comment by remy** [comment] 2015-05-21 06:29
I can't replicate this at all, so someone else will need to debug and send
a PR to fix. I'm hoping someone here will take up the challenge.

**Comment by nha** [comment] 2015-07-03 12:30
I have the same problem, using express/mongo as well.

Not sure if this is relevant, but I'll add it here : I'm in a vagrant virtual machine with nfs synchronisation of the filesystem.
http://docs.vagrantup.com/v2/synced-folders/nfs.html

Usually just stopping `nodemon`, wainting and launch it again fixes the problem.
I have this behaviour on a ubuntu or osx host, the target vagrant vm if ubuntu 12.04.

**Comment by remy** [comment] 2015-08-31 17:56
Please try the build here #625 and feedback against the issue #625.

**Comment by thedug** [comment] 2015-09-05 07:31
I'm seeing the problem as well and I'm also using vagrant with nfs

**Comment by remy** [comment] 2015-09-05 07:58
@thedug please can you test the latest dev build - details on #625

**Comment by thedug** [comment] 2015-09-05 09:03
@remy How do I load this test version?

**Comment by remy** [comment] 2015-09-05 16:49
Its at the top of this issue, in bold...

npm install -g nodemon@dev

**Comment by thedug** [comment] 2015-09-05 17:01
Thanks,

Does the nodemon@dev trick work if I'm using package.json?

**Comment by remy** [comment] 2015-09-05 18:10
I think so, I assume you mean as a local dependency.

**Comment by thedug** [comment] 2015-09-05 18:19
Yeah.. Do I just add the following to my package json?

nodemon: 'dev"

Also, I'm using grunt-nodemon, will it actually use this version or it's
own version?

**Comment by remy** [comment] 2015-09-05 19:01
I don't know about how other packages work. I'm not sure grunt-nodemon uses
peer dependencies, so you'll need to open an issue on their repo to ask for
a dev build version.

When I use nodemon as a direct dependency I'd install as simply `npm
install -D nodemon@dev`

**Comment by remy** [comment] 2015-09-12 10:44
#625 closes and released in `nodemon@1.4.2`

**Closed by remy** 2015-09-12 10:44 UTC

**Comment by ORESoftware** [comment] 2017-02-23 19:48
getting this in 2017, I have used nodemon a couple times before, not a newb with this, cannot figure out why it keeps restarting! will report back if I figure it out.

**Comment by tonespy** [comment] 2017-02-24 14:53
@ORESoftware I've been experiencing this for over a week now. And I don't seem to understand anymore either. I containerized my application and still the same thing.

**Comment by remy** [comment] 2017-02-24 17:11
Worth opening a new issue and including the nodemon version, node version, npm or yarn (doubt if it makes a difference), and OS.

**Comment by ORESoftware** [comment] 2017-02-25 00:23
I love Nodemon, the functionality it provides is critical to fast development.
I will come back to Nodemon, but if you need a script that does the job, you can use this

https://medium.com/@the1mills/diy-nodemon-5176fdcc1cfb#.t650qxq40

it was less time to write the script than to debug nodemon as is. I don't intend to undermine Nodemon, I simply intend to help people who might be in a bind like I was, I could not figure out why it keeps restarting. So bizarre.

**Comment by remy** [comment] 2017-02-25 17:30
You might be amazed at how simple (and short) the first version of nodemon
was. Scope creep eh? 🤔

**Comment by the1mills** [comment] 2017-02-25 18:47
I believe that! I saw hundreds of commits and 10s of branches and I was too afraid to look at the code as is. Now that I have tried my hand at I will take a look and the feature creep that took place!

One thing I definitely found that I wanted - as a user I would like to tell Nodemon whether I want Nodemon to send SIGTERM, SIGINT or SIGKILL to my process.

**Comment by remy** [comment] 2017-02-25 21:51
There's a PR in progress that lands that change. I think it's a little way
off though (it's mostly a clean up by a contributor).

**Comment by tonespy** [comment] 2017-03-01 21:28
@ORESoftware in my case, I noticed it's tracking my .tmp/ directory and `npm-log`. So, all I did was include a `.nodemonignore` and all the files I don't want to bother about.

**Comment by mdxprograms** [comment] 2017-07-16 03:58
@tonespy that worked for me as well

**Comment by ChrisEelmaa** [comment] 2017-08-17 12:50
still getting this. some info about my config: 

OSX
nodemon 1.11.0

my package json:

>     "dev": "concurrently \"npm run tstojs-watch\" \"npm run watch\"",
>     "tstojs-watch": "tsc -w",
>     "watch": "nodemon --watch dist --watch .env ./dist/index.js",

the command I run:

> npm run dev

It just keeps saying "restarting due to file changes" and then crashes.

some of the versions:
"concurrently": "3.1.0",
 "typescript": "2.3.4",

Don't have time to pursue it further at the moment, doing the manual compile & run method for now.

**Comment by arxpoetica** [comment] 2017-09-04 23:12
This seems to be happening on the latest version of Nodemon. I backed up to `1.11.0` and all systems go.

**Comment by jonasnas** [comment] 2017-11-25 21:46
I get this infinite loop if nodemon is run with `npm start => nodemon app.js` but it works fine if I run nodemon directly, which I eventually runs `npm start => node app.js`

**Comment by ORESoftware** [comment] 2017-11-25 22:47
Yeah I would avoid using `npm start` to start your app/server

**Comment by Airboy** [comment] 2017-12-26 22:24
I encountered the same issue. This bug is not related to `nodemon` but to another dependency: `user-agent`. This later regenerates on the fly a file based on a remote database ([regexps.js](https://github.com/3rd-Eden/useragent/blob/master/lib/regexps.js)). Because of it and the way it is generated, nodemon restart in loop.

By using the verbose mode in my `nodemon.json`, I was able to find the related file.

I hope this explanation should help others with this issue.

**Comment by arxpoetica** [comment] 2017-12-26 22:40
@Airboy not following. What do you mean by "verbose mode"?

**Comment by arxpoetica** [comment] 2017-12-26 22:40
And what's the correct way to fix this problem?

**Comment by Airboy** [comment] 2017-12-26 22:44
You merely have to add the following option `"verbose": false` into your `nodemon.json` (config file for nodemon).

In this mode, nodemon should display the file causing its restart. I don't guarantee that you can quickly solve your problem, but it's a good start to find the cause of this issue.

**Comment by remy** [comment] 2017-12-26 22:47
A fairly common example of nodemon looping restarts is when the application creates a file during start-up that's caught be nodemon watch filters, which triggers a restart, and then the entire process goes into a loop.

Run `nodemon --verbose` and it will report what's restarting the process and why (so you can explicitly ignore that file or pattern).

**Comment by arxpoetica** [comment] 2017-12-28 22:28
@remy yes, I've seen those problems happen before, and didn't equate the two. That was probably what was happening all along. False positive. Thanks.

**Comment by arxpoetica** [comment] 2018-01-03 11:23
Nope. I take it back. I ran verbose and files that are in `.nodemonignore` are no longer ignored on the upgrade.

Am I doing the pattern wrong?

```
/client/*
/public/*
```

**Comment by remy** [comment] 2018-01-03 11:33
@arxpoetica I think that's an absolute path, so assuming that `/public` is at the root of your drive, then it should work. Otherwise try `./public/*`.

**Comment by arxpoetica** [comment] 2018-01-03 11:33
I found the problem. It's reading `package.json` before `.nodemonignore` `-->`

```
[nodemon] reading config /Users/.../package.json
```

Why would it do that if I don't have a nodemonignore file already?

**Comment by arxpoetica** [comment] 2018-01-03 11:35
I mean, I can just switch to the modern convention, which is what I'll do. (Tho' I prefer the old way.)

**Comment by remy** [comment] 2018-01-03 11:35
Oh yes, if there's `nodemonConfig` in the `package.json`, then IIRC that will take over.

**Comment by remy** [comment] 2018-01-03 11:37
Wait…sorry, I spoke too early. That log just means it's _checking_. I'm just checking the source code now…

**Comment by arxpoetica** [comment] 2018-01-03 11:39
To be clear, I don't have `nodemonConfig` in `package.json`

**Comment by remy** [comment] 2018-01-03 11:40
I'm reading the code (and will open a new issue) because the logging around *where* the config came from isn't clear (at all!).

Can you run your nodemon command (as you are already) but with `--dump` and include the output here? It'll help me see whether it read a config or not.

**Comment by arxpoetica** [comment] 2018-01-03 11:42
Yup. Probably good to still open an issue, though I just got it working correctly!

**Comment by arxpoetica** [comment] 2018-01-03 11:45
Here it is:

```bash
[nodemon] 1.14.7
[nodemon] reading config /Users/[...directory info removed...]/package.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 13348 to restart
[nodemon] ignoring: **/.git **/.nyc_output **/.sass-cache **/bower_components **/coverage **/node_modules
[nodemon] watching: *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node -r @std/esm server.js`
[nodemon] spawning
[nodemon] child pid: 13350
[nodemon] watching 329 files

[nodemon] files triggering change check: client/source/app/components/NewsList.pug
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/0
[nodemon] files triggering change check: client/source/app/components/NewsList.html
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/0
[nodemon] files triggering change check: public/js/app.js.map
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/0
[nodemon] files triggering change check: public/js/app.js
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] restarting due to changes...
[nodemon] public/js/app.js

[nodemon] starting `node -r @std/esm server.js`
[nodemon] spawning
[nodemon] child pid: 13372
```

**Comment by remy** [comment] 2018-01-03 11:47
That wasn't the `--dump`, but it's fine if you've got it sorted 😉

**Comment by arxpoetica** [comment] 2018-01-03 11:48
Yeah, sorry, I figured that out right after I posted (and promptly deleted). Here's the actual dump:

```bash
[nodemon] 1.14.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v9.2.0
nodemon: 1.14.7
command: /Users/americanyak/.nvm/versions/node/v9.2.0/bin/node /Users/[...path ommitted...]/project-y/node_modules/.bin/nodemon --dump -r @std/esm server.js
cwd: /Users/[...path ommitted...]/project-y
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/[...path ommitted...]/project-y' },
  required: false,
  dirs:
   [ '/Users/[...path ommitted...]/project-y' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git',
        '**/.nyc_output',
        '**/.sass-cache',
        '**/bower_components',
        '**/coverage',
        '**/node_modules',
        re: /.*.*\/\.git|.*.*\/\.nyc_output|.*.*\/\.sass\-cache|.*.*\/bower_components|.*.*\/coverage|.*.*\/node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git',
        '**/.nyc_output',
        '**/.sass-cache',
        '**/bower_components',
        '**/coverage',
        '**/node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: 'server.js',
        exec: 'node',
        args: [ '-r', '@std/esm' ],
        scriptPosition: 2,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git',
        '!**/.nyc_output',
        '!**/.sass-cache',
        '!**/bower_components',
        '!**/coverage',
        '!**/node_modules' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded:
   [ '/Users/[...path ommitted...]/project-y/package.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ '-r', '@std/esm', 'server.js' ] },
     string: 'node -r @std/esm server.js' } }
--------------
```

**Comment by dotspencer** [comment] 2018-08-22 05:12
My two bits... Try updating nodemon.
I was using v1.11 and upgrading to v1.18.3 fixed the issue.

**Comment by dionisoros** [comment] 2019-10-25 13:34
My solution: add **nodemonConfig** in **package.json** file in order to stop infinite loop. In **package.json**: 
`  "nodemonConfig": {
    "ext": "js",
    "ignore": ["*.test.ts", "db/*"],
    "delay": "2"
  },
  "scripts": {
    "start": "nodemon"
  },`

**Comment by grandmaximum** [comment] 2023-11-17 08:59
> My solution: add **nodemonConfig** in **package.json** file in order to stop infinite loop. In **package.json**: ` "nodemonConfig": { "ext": "js", "ignore": ["*.test.ts", "db/*"], "delay": "2" }, "scripts": { "start": "nodemon" }`

{ "scripts": { "start": "nodemon"} was what solved the problem for me!
