### ISSUE TITLE
Nodemon stuck on restarting due to changes...

### ISSUE THREAD

**Issue by Balestra78** [remy/nodemon#1971] opened 2022-01-19 17:35 UTC
Hi, i tried with npm i nodemon@debug
in the package json i can see 

{
  "dependencies": {
    "aws-sdk": "^2.1058.0",
    "express": "^4.17.2",
    "nodemon": "^2.0.14-alpha.1",
    "uuid": "^8.3.2"
  }
}

but with nodemon -v i get 1.19.4

the script i ran it's very simple

```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('AAAHellodwddcc')
})

app.listen(port, () => {
  console.log(`Example Test listening at http://localhost:${port}`)
})
```

- Versions: 
- node@v16.13.2, win32@10.0.19042
- `nodemon -v`:
- 1.19.4
- Operating system/terminal environment (powershell, gitshell, etc): 
Windows10 / VS Code
- Using Docker? What image: no Docker
- Command you ran: nodemon server.js

### Expected behaviour
restarting server and refresh web page

### Actual behaviour
stuck to [nodemon] restarting due to changes... and no refresh

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by EmptyBox12** [comment] 2022-01-22 19:21
I am having the same issue

**Comment by QaziTalha4595** [comment] 2022-01-24 10:17
I have the same problem

**Comment by omgcx1222** [comment] 2022-01-28 14:00
Have you solved this problem

**Comment by omgcx1222** [comment] 2022-01-29 00:59
> @omgcx1222我还在使用 windows 终端，这不是那么烦人：启动 nodemon 一次，我继续

I'm also using Windows terminals, Add C:\windows and C:\windows\system32 to the Path of system variable, It can solve the problem

**Comment by omgcx1222** [comment] 2022-01-29 01:01
> @omgcx1222 i'm still using windows terminal, it's not so annoying: start nodemon one time and i go on

I'm also using Windows terminals, Add C:\windows and C:\windows\system32 to the Path of system variable, It can solve the problem

**Comment by lorand-horvath** [comment] 2022-01-30 08:13
If you run `nodemon -v` and get 1.19.4, it seems you have that old nodemon version installed globally on Windows.
If you want to run/use the locally installed version, which seems to be 2.0.14-alpha.1, you have to add a script in your local package.json something like this:
scripts: {
    "nodemon": "nodemon index.js"
}
Running `npm run nodemon` will launch your locally installed nodemon binary, not the global version.

Otherwise, I'd just update the global version with `npm install -g nodemon` and run as usual `nodemon index.js`

**Comment by omgcx1222** [comment] 2022-01-30 08:45
> If you run `nodemon -v` and get 1.19.4, it seems you have that old nodemon version installed globally on Windows.
> 
> If you want to run/use the locally installed version, which seems to be 2.0.14-alpha.1, you have to add a script in your local package.json something like this: `scripts: { "nodemon": "nodemon server.js" }` Running `npm run nodemon` will launch your locally installed nodemon binary, not the global version.
> 
> Otherwise, I'd just update the global version to latest 2.0.15 with `npm install -g nodemon@2` and run as usual `nodemon server.js`

That's how I run, But it can't. stuck on ---> [nodemon] restarting due to changes...

**Comment by lorand-horvath** [comment] 2022-01-30 09:40
> That's how I run, But it can't. stuck on ---> [nodemon] restarting due to changes...
That's how you run - how exactly? What is what you call 'that'?
But it can't - what it can't do? Who is that which can't do? Who is it?
OK, can you be more explicit, please? This is not a chatroom.

**Comment by lorand-horvath** [comment] 2022-01-30 09:46
Duplicate of https://github.com/remy/nodemon/issues/1956

**Comment by omgcx1222** [comment] 2022-01-30 11:06
@lorand-horvath  add a script in  local package.json:  `scripts: { "start": "nodemon server.js" }` Running `npm start`  stuck on ---> [nodemon] restarting due to changes...   Now I have solved it in my own way![https://github.com/remy/nodemon/issues/1971#issuecomment-1025097207](url)

**Comment by lorand-horvath** [comment] 2022-01-30 13:17
@omgcx1222 Glad you solved it! You may close this issue, then.

**Comment by Balestra78** [comment] 2022-01-31 16:21
> npm install -g nodemon@2

@lorand-horvath i launched this command and now it seems to work fine, thanks a lot

**Comment by Balestra78** [comment] 2022-01-31 16:23
i launched `npm install -g nodemon@2` as @lorand-horvath wrote, and now it seems to work fine, thanks a lot

**Closed** 2022-01-31 16:22 UTC
