### ISSUE TITLE
Many restarting after any simple change

### ISSUE THREAD

**Issue by romaniv1024** [remy/nodemon#1368] opened 2018-06-20 09:21 UTC
- `nodemon -v`: 1.17.5
- `node -v`: 9.5.0
- Operating system/terminal environment: windows 10
- Command you ran: nodemon app.js

After any simple change (even type space) have many restarting

my code
![image](https://user-images.githubusercontent.com/22196861/41649277-ec5bf88c-7483-11e8-8b46-3b5b2a952c8c.png)

terminal
![image](https://user-images.githubusercontent.com/22196861/41649378-1bff54a8-7484-11e8-977a-93c79e8b8ee4.png)

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment] 2018-06-20 13:06
Can you rerun with `--verbose` flag so we can see what's causing the
restart?

**Comment by romaniv1024** [comment] 2018-06-20 15:04
Yes
![image](https://user-images.githubusercontent.com/22196861/41666914-4ff27d00-74b4-11e8-9112-7e5b46436ecb.png)

**Comment by remy** [comment] 2018-06-22 10:04
This is actually a dupe of #1354

**Closed by remy** 2018-06-22 10:04 UTC
Labels: windows
