### ISSUE TITLE
nodemon doesn't accept filename having hyphen [-]

### ISSUE THREAD

**Issue by kk7drift** [remy/nodemon#1233] opened 2018-01-23 12:08 UTC
- `nodemon -v`: 1.14.11
- `node -v`: v9.4.0
- Operating system/terminal environment: Win 7-64 bit
- Command you ran: nodemon .\arrow-functions.js

### Actual behaviour
![image](https://user-images.githubusercontent.com/20459964/35274716-2eb02478-0063-11e8-98a8-6aacc05e97cf.png)

### Expected behaviour
-Command you ran: nodemon .\arrow_functions.js
When I run the same command by removing the hyphen in the file name, the command works as expected. 
![image](https://user-images.githubusercontent.com/20459964/35274845-aca151ae-0063-11e8-8d44-bf88d111ab08.png)

### Steps to reproduce
I have used Visual studio code as IDE and used following code in arrow-functions.js
![image](https://user-images.githubusercontent.com/20459964/35274908-ee4df4fe-0063-11e8-92ad-c431f2f9b9d5.png)
1. Execute nodemon with any js file name having a hyphen.

**Comment by remy** [comment] 2018-01-23 12:54
Very weird! I'll check that out.

**Comment by sepacraig** [comment] 2018-01-30 14:12
nodemon -v: 1.14.11
node -v: v8.94
Operating system/terminal environment: Win 7-64 bit

The following works ok for me

Windows Shell
`nodemon .\arrow-functions.js`

Bash Shell

`nodemon ./arrow-functions.js`

**Comment by remy** [comment] 2018-01-30 14:30
Possible node@9 issue then?

**Comment by remy** [comment] 2018-02-01 18:09
I can't replicate this at all. I'm running the same powershell and version of node and cannot reproduce.

The screenshot you originally provided shows that powershell is claiming that it can't find node (the source of the error), and I suspect there's something bespoke about either your node setup or powershell setup. 

This was my test: 

![powershell-1233](https://user-images.githubusercontent.com/13700/35694953-e40a3764-077a-11e8-8998-491fe122f958.png)

I'm going to close this this as it can't be replicated **and** you have a work around (though not ideal). Unless there's others with the same issue, I can't help you and, again, I suspect this is bespoke to your setup.

**Closed by remy** 2018-02-01 18:09 UTC
Labels: bug, windows

**Comment by kk7drift** [comment] 2018-02-13 11:28
I think the issue was with my setup

Once I updated my nodemon package to 1.14.12
I was able to run the file[filename having hyphen] with nodemon.

Thanks remy

**Comment by remy** [comment] 2018-02-13 11:48
That's reassuring to hear 👍
