### ISSUE TITLE
node v8.9.3 - error No valid versions available for is-retry-allowed

### ISSUE THREAD

**Issue by jfloresanchez** [remy/nodemon#1209] opened 2018-01-06 19:06 UTC
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment: 
- Command you ran:

### Steps to reproduce

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment] 2018-01-06 20:03
Closing as dupe of #1210

**Closed by remy** 2018-01-06 20:03 UTC
