### ISSUE TITLE
"ignored" custom/default pattern ignored under Windows

### ISSUE THREAD

**Issue by Lucas-C** [remy/nodemon#1248] opened 2018-02-06 12:58 UTC
- `nodemon -v`: 1.14.12
- `node -v`: v8.9.4
- Operating system/terminal environment: Windows 10 terminal with Cmder
- Command you ran: `nodemon ./src/server.js`

### Expected behaviour
Not so many logs

### Actual behaviour
Hundreds of log lines indicating that files under `node_modules/` are beeing watched:
```
nodemon ignored [ '**/.git/**',
  '**/.nyc_output/**',
  '**/.sass-cache/**',
  '**/bower_components/**',
  '**/coverage/**',
  '**/node_modules/**',
  'node_modules/*',
  re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*|node_modules\/.*/ ]
...
  nodemon:watch watching dir: node_modules\use\node_modules\is-data-descriptor\node_modules\kind-of\index.js +5ms
  nodemon:watch watching dir: node_modules\use\node_modules\is-data-descriptor\node_modules\kind-of\package.json +5ms
  nodemon:watch watching dir: node_modules\ncp\test\symlink-fixtures\src\dir\bar +6ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-data-descriptor\node_modules\kind-of\LICENSE +5ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-data-descriptor\node_modules\kind-of\README.md +5ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-data-descriptor\node_modules\kind-of\index.js +6ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-data-descriptor\node_modules\kind-of\package.json +6ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-accessor-descriptor\node_modules\kind-of\LICENSE +5ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-accessor-descriptor\node_modules\kind-of\README.md +7ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-accessor-descriptor\node_modules\kind-of\index.js +5ms
  nodemon:watch watching dir: node_modules\snapdragon\node_modules\is-accessor-descriptor\node_modules\kind-of\package.json +6ms
  nodemon:watch watching dir: node_modules\static-extend\node_modules\is-data-descriptor\node_modules\kind-of\LICENSE +6ms
  nodemon:watch watching dir: node_modules\static-extend\node_modules\is-data-descriptor\node_modules\kind-of\README.md +6ms
  nodemon:watch watching dir: node_modules\static-extend\node_modules\is-data-descriptor\node_modules\kind-of\index.js +7ms
  nodemon:watch watching dir: node_modules\static-extend\node_modules\is-data-descriptor\node_modules\kind-of\package.json +5ms
```

### Root cause
Because `nodemon` use `chokidar` 2, it is affected by this bug that is in the process of being resolved:
https://github.com/paulmillr/chokidar/pull/669

**Comment by remy** [comment] 2018-02-06 15:08
You're running with `DEBUG=nodemon:watch` right? So you've enabled deep debugging…?

**Comment by Lucas-C** [comment] 2018-02-06 15:15
Yes, sorry, the issue is not so much with the verbose logging than with the fact that `nodemon` monitors the `node_modules` directory. Which it shouldn't given the default `ignored` patterns. And watching so many files may be detrimental to the performances.
Should I close this issue ?

**Comment by remy** [comment] 2018-02-07 11:58
No, don't close the issue, but the actual issue, if I'm reading correctly is this:

> Windows isn't ignore node_modules correctly (looks like a path/slash issue)

I'll try to take a stab at it during the weekend, unless you're able to take a look and raise a PR.

**Comment by Lucas-C** [comment] 2018-02-07 13:15
Yes, your description of the actual issue is correct.

As I mentionned, I think there is already a PR downstream to fix the underlying issue: paulmillr/chokidar#669

**Comment by remy** [comment] 2018-02-13 08:41
Doh, misread - but yeah, my PR had been merged, but not released. It got release just last week and I'm pushing a nodemon release this week to update.

I'm going to close this as a dupe of #1225 (so that it's tracked in a single place).

**Closed by remy** 2018-02-13 08:41 UTC
Labels: bug, windows
