### ISSUE TITLE
listen EADDRINUSE version 1.8.0

### ISSUE THREAD

**Issue by kiro112** [remy/nodemon#702] opened 2015-10-26 10:00 UTC
nodemon server.js
- at first it run normally
- but when try to resave file/update files it wont rerun

then ctrl+c to stop nodemon
then rerun script again via nodemon server

and it looks like the port is not killed
it gives the error "listen EADDRINUSE"

**Comment by Niklas81** [comment] 2015-10-26 11:28
I can confirm that 1.8.0 no longer restarts on file change, however I can use command `rs` to manually restart it, or `ctrl+c` to stop it. When restaring it, I do not get any error. So to me, it's just the auto-restart that stopped working with last update to 1.8.0

**Comment by davidgatti** [comment] 2015-10-26 11:34
Same here.

**Comment by remy** [comment] 2015-10-26 11:56
@davidgatti that isn't used in 1.8.0 anymore: https://github.com/remy/nodemon/blob/v1.8.0/lib/monitor/watch.js

I'm not completely clear on what people are seeing here. Can someone put together a sample script, and repeatable actions to debug with?

**Comment by davidgatti** [comment] 2015-10-26 11:58
There isn't much to it. start nodemon, change a file in your project, save it, and you will see that nodemon doesn't react to the change.

I downgraded to 1.7.3 and works with no problem.

**Comment by Niklas81** [comment] 2015-10-26 12:27
Like @davidgatti said; downgrade and it works again. So whatever was added or removed to v 1.8.0 broke it.

**Comment by prashaantt** [comment] 2015-10-26 13:56
+1. Downgrading to 1.7.3 restores file watch functionality.

**Comment by kiro112** [comment] 2015-10-26 14:09
Hi @remy 

very simple App : https://gist.github.com/kiro112/e06d08f3c977fb4723e1
run with nodemon

tested in
node 0.10.33

nodemon gives error
[nodemon] Internal watch failed: watch ENOSPC


in node v4.2.1
[nodemon] Internal watch failed: watch file_path ENOSPC


i hope it helps.
thanks

**Comment by martinduparc** [comment] 2015-10-26 20:18
Confirming that this is an issue with v1.8.0 (no error message displayed)

**Comment by JasonLough** [comment] 2015-10-26 22:37
To reporduce and then break and then get working again...

//////////confirm everything should work :

Fresh install of express 4.

cd bin && node www

reload 127.0.0.1:3000, 'Welcome to Express' shows up

ctrl C

reload 127.0.0.1:3000, 'Page not found', confirming it shut down

node www

reload 127.0.0.1:3000, 'Welcome to Express' shows up

///////////breaking it :

fresh install of nodemon 1.8.0

Exact same install of Express 4 above. 

node NOT listening on port 3000. (confirm with lsof -i :3000, which comes back with nothing)

nodemon

[nodemon] 1.8.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
[nodemon] Internal watch failed: watch ENOSPC

lsof -i :3000

COMMAND   PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    29194 jason   12u  IPv6 1167495      0t0  TCP *:3000 (LISTEN)

node bin/www

Port 3000 is already in use

kill 29194

node bin/www

//interestingly, no errors here

reload 127.0.0.1:3000, 'Welcome to Express' shows up

**Comment by AlexZeitler** [comment] 2016-01-22 17:14
@JasonLough This fixed it for me as well. :+1:

**Comment by betaorbust** [comment] 2016-03-23 23:52
Just ran into this as well. 
**Node**: 4.2.1.
**Nodemon**: 1.9.1
**Results**: EADDRINUSE error. 
Running `lsof -i tcp:<port number>` I get back that node is running there. Killing it via PID is the only way to get my server back and running.

**Node**: 4.2.1
**Nodemon**: 1.7.3
**Results**: Everything shuts down correctly.

This issue is currently marked as `needs more info`. Is there other information we can provide? It looks like there are repro cases and reports going back five months.

**Comment by VtoCorleone** [comment] 2016-04-02 19:34
Got the same issue -

**Node**: 4.4.0
**Nodemon**: 1.9.1
**Result**: EADDRINUSE

**Node**: 4.4.0
**Nodemon**: 1.7.3
**Result**: expected behvior

**Comment by remy** [comment] 2016-04-02 21:37
If you're able to replicate consistently would it be possible to roll the
version back gently until you find the regression? From there the diff
between versions might be enough to solve this issue.

**Comment by xavdid** [comment] 2016-06-22 22:26
I'm getting this issue (tried it with versions `1.9.0`, `1.8.1`, and `1.7.3`), when used in conjunction with foreman, watchify, and typescript.

My Procfile looks something like this: 

```shell
# watches all server js
server: PORT=1337 nodemon --delay 2 --ignore client.js --ignore public/_bundle.js
# watches the client and re-browserifys on change
client: watchify client.js -v -o public/_bundle.js
# watches all .ts files and retranspiles them.
typescript: tsc -w
```

So, `tsc` should trigger the other two processes to act on their (separate) files. Nodemon starts the first time, but on any subsequent rebuild, I get the EADDRINUSE when it tries to start the server. An `rs` usually fixes it, but that defeats the purpose of using an auto restart tool in the first place, haha.

**Comment by rifton007** [comment] 2016-07-08 04:24
Same problem for me
node 6.3.0
nodemon 1.9.2
Thank for your help

**Comment by ggregoire** [comment] 2016-10-20 23:29
Hey,

I can confirm the problem and the solution.

Was in `1.10.2` and got the error randomly.

Now in `1.7.3` and the problem seems gone.

**Comment by bonesoul** [comment] 2016-12-21 18:05
having the same issue

**Comment by chantlong** [comment] 2017-04-21 12:50
same issue.

setup
`Node 7.8.0`
`Nodemon 1.11.0`

when running
`nodemon server/index.js --exec babel-node --presets latest`

dies on a few restarts.

**Comment by yezongyang** [comment] 2017-05-27 08:43
same issue.

setup
Node 7.10.0
Nodemon 1.11.0

when running resave file

**Comment by melDavila** [comment] 2017-06-22 18:16
Same issue.
When running  and a file has change in the server 

server  setup
Node 7.10.0
Nodemon 1.11.0

on local.  version 6,10,3 Works 
Node 6.10.3
Nodemon 1.11.0

**Comment by bmtKIA6** [comment] 2017-06-25 21:41
Try adding the following to your app

`
process.on('SIGUSR2', () => { process.exit(0); });
`

**Closed** 2017-12-12 15:20 UTC
Labels: needs more info, wontfix

**Comment by Nnanyielugo** [comment] 2018-02-10 09:31
Problem still exists.

**Comment by remy** [comment] 2018-02-11 14:32
@Nnanyielugo then perhaps you can provide a reproducible example with code, or better yet, a PR to help resolve the problem you're seeing?

**Comment by capaj** [comment] 2018-03-28 14:10
@Nnanyielugo I had it today. I think it occured because I had a "zombie" nodemon process running in the background which was fighting with the one I had in my console. Try restarting your computer.

**Comment by mqliutie** [comment] 2018-07-06 08:45
Many days ago everything is fine.(Because I have to word)
Today I had it.

`nodemon --experimental-modules ./app.mjs`

**Comment by lacivert** [comment] 2018-07-31 18:29
I have been using the same script for almost one year. Now this is happening these days and I don't know why. it happens only in one project. I was using nodemon version 1.17, now I have upgraded to 1.18, it still happens without a reason. I am getting mad

**Comment by natasjja** [comment] 2018-09-19 01:54
> Try adding the following to your app
> 
> `process.on('SIGUSR2', () => { process.exit(0); });`

This worked, but can you explain to me why it works please? 😄

**Comment by oehm-smith** [comment] 2019-04-16 06:27
@natasjja Signals with regard to processes reports the occurrence of an exceptional event.  For example SIGINT signal is sent when the user types Ctrl-C (https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#Termination-Signals).  The operating system sends these and applications receive them.  In some cases the application can respond to the signal, but in others such as SIGKILL it is final and the app will be terminated.

Node passes on signals through event handling (`process.on()`).

`SIGUSR2` is a user-defined (ie. nodemon here) signal that is sent by nodemon upon restart.

As per https://github.com/remy/nodemon#controlling-shutdown-of-your-script, it can be monitored and acted upon in your application.  In the example you provided, it explicitly kills the current app process and then nodemon restarts the application cleanly.
