### ISSUE TITLE
Nodemon is starting with not defined file.

### ISSUE THREAD

**Issue by metinsut** [remy/nodemon#1504] opened 2019-01-14 08:30 UTC
- nodemon -v: 1.18.9
- node -v: 11.4.0
- Operating system/terminal environment: Windows 10 / Terminus 1.0.68
- Command you ran: "npm start":"npm-run-all -p watch:*"

### Expected behaviour
I just want to run the command that I wrote to the package.json file.

### Actual behaviour
Nodemon is starting with two file dev/index and build/index
Why nodemon is runnig build/index.js ?

`[nodemon] 1.18.9`
`[nodemon] to restart at any time, enter "rs"`
`[nodemon] watching: *.*`
`[nodemon] starting "node dev/index.js build/index.js"`

### Steps to reproduce
I would like to work only dev/index.js file.

```
"scripts": {
	"start": "npm-run-all -p watch:*",
	"build": "webpack --config webpack/webpack.prod.js",
	"watch:ts": "webpack --config webpack/webpack.dev.js --watch",
	"watch:node": "nodemon dev/index.js"
},
```

**Comment by metinsut** [comment] 2019-01-14 11:32
> And what happens when you run `npm run watch:node`?

```
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node dev/index.js`
```
Now worked correctly.
Probbably happening when you first time run "npm run build"
What does that have to do with that run "npm run build" ?
I didn't figure out anything.

**Comment by remy** [comment] 2019-01-14 12:06
IDK - I'm guessing it's to do with your `npm-run-all` command. Again, guessing a little since I don't use the utility myself, it looks like it's passing a param into the `npm run watch:node` script, but not sure why (again, no knowledge of this lib).

Since when you run it without the `npm-run-all` it's working as expected, it tells me there's nothing wrong with nodemon itself and the issue is outside somewhere. 

One last thing you can check before I close this issue (I'd suggest raising a question with the maintainer(s) of `npm-run-all`) - do you have a `nodemon.json` file, and can you paste it here if you do? I doubt if this is a factor, but worth ruling it out.

**Comment by metinsut** [comment] 2019-01-14 13:16
Thanks Remy, I will check out this issue later. But now you can close this issue.

**Closed** 2019-01-14 15:44 UTC
