### ISSUE TITLE
[BUG] Nodemon ^2.0.9  giving error "UnhandledPromiseRejectionWarning: Error: Command failed: wmic process " on UPDATING file in  Windows 10 machine

### ISSUE THREAD

**Issue by indranil786** [remy/nodemon#1881] opened 2021-07-06 20:52 UTC
- `nodemon -v`:  2.0.9
- `node -v`: 14.16.1
- Operating system/terminal environment:  WIndows ( both on Git Bash and Windows Powersell)
- Command you ran: npm start
- The nodemon is working as expected when I start the server, using it. However when I am updating/changing my index file, and is Saving. It throws me the error. 

### Expected behaviour

Restart the sever after any change is made to index file and saved.
</br>
![npm 2 07](https://user-images.githubusercontent.com/62298458/124664125-9cc65080-dec8-11eb-87d1-132df5ad3a65.jpg)
</br>
 
This problem is not persisting in Nodemon version  2.0.7;

### Actual behaviour
When I am trying to  save/make change, it is throwing me an error

```bash
[nodemon] restarting due to changes...
(node:8648) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=6160) get ProcessId 2> nul
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)......
```
![nodemon_issue](https://user-images.githubusercontent.com/62298458/124664830-9dabb200-dec9-11eb-877c-b9d032553658.jpg)
<br>
### Steps to reproduce

This is the package.json file  that I am using.
```json
{
  "name": "socket-basics",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon ./index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "nodemon": "^2.0.9",
    "uuid": "^8.3.2"
  }
}

```

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment] 2021-07-06 21:53
Dupe of #1875 - but please add any extra info to that thread, and please try the debug build.

**Closed by remy** 2021-07-06 21:53 UTC
