### ISSUE TITLE
Nodemon serving root index.html despite  config to serve public/index.html

### ISSUE THREAD

**Issue by joshua-fogg** [remy/nodemon#1108] opened 2017-10-02 23:49 UTC
Hey I am trying to use an express server to build my React App for a github blog. I am finding that Nodemaon is trying to serve my git project root folder index file despite defining to serve from the public folder.  I have figured out that it is coming from somewhere within Nodemon or its dependencies. I could not find the `node index.html` script in the node_module nodemon package.json.

Any insights would be greatly appreciated.
**server.js**
```
 var express = require('express')
 var server = express()

 var path = require('path')

 var PORT = 3000

 server.use(express.static('public'))

 server.listen(PORT, function () {
   console.log('Listening on port', PORT)
 })
```
**package.json script**
``
**Terminal**
```
eda@mini2 ~/workspace/joshua-fogg.github.io  ‹master*›
╰─$ npm run dev2                                                                                                                     130 ↵

> joshua-fogg.github.io@1.0.0 dev2 /home/eda/workspace/joshua-fogg.github.io
> nodemon --watch ./server.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ./server.js
[nodemon] starting `node index.html`
/home/eda/workspace/joshua-fogg.github.io/index.html:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
                                                              ^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by remy** [comment] 2017-10-03 06:42
That's weird. Particularly as you gave it what file to run.

Can you paste your package.json here too?

**Comment by remy** [comment] 2017-12-04 22:13
Idle. Closing, but pretty sure the problem is in the package.json

**Closed by remy** 2017-12-04 22:13 UTC
