### ISSUE TITLE
EPERM while executing nodemon on new Bash on Windows 10 feature

### ISSUE THREAD

**Issue by knwabueze** [remy/nodemon#859] opened 2016-06-16 20:33 UTC
I am using ZSH on the new Bash on Windows 10 and whenever i run nodemon it still runs but it gives me this error and still allows me to use to command line

```
Command: sudo nodemon index.js
Output: [nodemon] Internal watch failed: watch (current directory) EPERM
```

Nodemon Dump Output:

```
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
--------------
node: v4.4.5
nodemon: 1.9.2
command: /usr/local/bin/node /usr/local/bin/nodemon index.js --dump
cwd: /mnt/d/sandbox/Web Projects/studious-carnival
OS: linux x64
--------------
{ run: false,
  system: { cwd: '/mnt/d/sandbox/Web Projects/studious-carnival' },
  required: false,
  dirs: [ '/mnt/d/sandbox/Web Projects/studious-carnival' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!/mnt/d/sandbox/Web Projects/studious-carnival/.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!/mnt/d/sandbox/Web Projects/studious-carnival/node_modules/**/*' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command:
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }
```

**Comment by wellguimaraes** [comment] 2016-06-17 18:50
I'm having this problem too. Are you running Win10 on a VM?

**Comment by Scruffin** [comment] 2016-06-18 00:38
No, I am just running the new Insider Build with the Bash feature.

**Comment by tanepiper** [comment] 2016-06-20 10:56
Can confirm I am getting the same issue with Bash On Ubuntu for Windows

**Comment by jackmasa** [comment] 2016-06-29 10:43
+1

**Comment by knwabueze** [comment] 2016-07-09 01:09
No reason for this to be open

**Comment by tanepiper** [comment] 2016-07-13 09:15
@knwabueze Why? Do you have a solution to this?

**Comment by jdrydn** [comment] 2016-07-15 11:19
Yeah I'm also getting this issue, although I reckon it could be more to do with Bash for Windows than actually a `nodemon` error.

@knwabueze A clearer message would be appreciated, just closing the issue with no real explanation isn't supportive?

**Comment by knwabueze** [comment] 2016-07-17 02:56
Sorry for not clarifying, I couldn't solve it out and just decided it would be better for me to switch to using a different shell. I couldn't do too much I'm still pretty new to Node.js

**Comment by jackchammons** [comment] 2016-07-29 21:44
@knwabueze It looks like this is a problem with the Windows Subsystem for Linux. Would you mind filing this issue with us? 

https://github.com/Microsoft/BashOnWindows/issues

**Comment by YasharF** [comment] 2016-08-15 11:20
Has anyone tried the solution at http://stackoverflow.com/questions/34662574/node-js-getting-error-nodemon-internal-watch-failed-watch-enospc

**Comment by YasharF** [comment] 2016-08-15 11:22
Related: https://github.com/Microsoft/BashOnWindows/issues/723 and https://github.com/Microsoft/BashOnWindows/issues/216

**Comment by YasharF** [comment] 2016-08-15 11:29
It looks like in cases like with rails, they have workarounds in the meantime.  Is there a way to have a workaround for Nodemon?

**Comment by jopcode** [comment] 2016-11-07 04:21
same error, some solution? :/

**Comment by YasharF** [comment] 2016-11-07 05:20
I can confirm that this is resolved in the latest builds of Windows 10 (I'm running 14959 atm), but those builds are still part of the Fast Ring Insider Preview program, and have other known issues.

**Comment by Naoto-Ida** [comment] 2017-03-11 13:39
I don't use zsh either, but this still seems to be happening.

**Comment by computersarecool** [comment] 2017-04-29 22:29
I am running the absolute latest version of Windows 10 (170424-221 atm) and I still have issues, in Bash as well I get: `npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

**Comment by YasharF** [comment] 2017-04-29 22:53
@computersarecool  what you posted seems to be a different issue than this github issue which is tracking the error "[nodemon] Internal watch failed: watch (current directory) EPERM".

**Comment by computersarecool** [comment] 2017-04-29 22:55
Indeed. Another issue with a similar focus listed this as a duplicate.  However, my issue is different and does not belong here.

**Comment by computersarecool** [comment] 2017-04-29 22:55
You are correct. I removed my post.

**Comment by mrminecart** [comment] 2017-06-16 09:38
Same issue :/

**Comment by izikandrw** [comment] 2017-09-05 05:08
this is happening to me TT

**Comment by whitneyland** [comment] 2017-09-08 16:51
One more bit of info:
Still happening in Windows 10.0.15063
Microsoft fix (thought to be related) has completed for a while: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

**Comment by YasharF** [comment] 2017-09-11 18:16
The original issue was fixed with changes from Microsoft about a year ago, and I have not had an issue since.  Are all of your software including the linux subsystem, system packages (apt-get), and globally installed npm packages up to date?  Can you provide log/dump of the output?  The following is my current setup which the problem is no longer present in.

======= My Windows version when I open CMD
`Microsoft Windows [Version 10.0.15063]`

======= My WSL version:
```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

======= My linux package status:
```
$ sudo apt-get update && sudo apt-get upgrade
[sudo] password for {redacted username}:
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 https://cli-assets.heroku.com/branches/stable/apt ./ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:4 https://deb.nodesource.com/node_6.x xenial InRelease
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Fetched 204 kB in 1s (120 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libegl1-mesa libgbm1 libgl1-mesa-dri libmirclient9 libwayland-egl1-mesa
  nodejs
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```

======= My node version:
```
$ nodejs -v
v6.11.2
```

======= My global npm updatestatus:
```
$ sudo npm update -g
{blank response since everything was up to date}
```

======= My global npm packages and their versions:
```
$ sudo npm list -g --depth=0
/usr/lib
---- nodemon@1.12.0
---- npm@5.4.1
```

======= What I am getting when I run nodemon:
```
$ nodemon
[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
Listening on port 3001
```

**Closed** 2017-12-12 14:20 UTC
Labels: wontfix
