### ISSUE TITLE
nodemon not restart when files changed in Some directory

### ISSUE THREAD

**Issue by mgrush** [remy/nodemon#818] opened 2016-04-15 08:49 UTC
Today , I tried to run  `nodemon app.js`, it goes right at the first time but not auto restart when the `app.js` file is changed !

```
nodemon app.js
```

This is the code of `app.js` : 

```
var http = require("http");
var server = http.createServer(function(req, res){  
    res.end("Hello World !");
});

server.listen(3000);
```

At last , I found that : 

`It runs differently in different dirs, Such as : it runs perfectly in dir A , but not auto start in dir B` . I really don't understand WHY ?

**Comment by remy** [comment] 2016-04-15 09:57
What's in dir B?

**Comment by mgrush** [comment] 2016-04-15 10:02
@remy I run my app.js use nodemon in two different directories : 

```
A : /home/www/mgrush.github/node-mgrush.github.com
B : /home/www/yuquan.caimi-inc.com
```

The same code, but the result is different : 

In the A directory, It starts normal but not auto restart when changes happend ~
In the B directory , It goes perfectly  and auto restart when changes happend ~

I don't know if this happens relating to the permission of the different directories ~ 

THANK YOU !

**Comment by dochang** [comment] 2016-04-24 00:55
+1

I think it's a duplicate of #808 .

The problem is the `.git` part in the directory name.

**Closed** 2017-12-12 18:26 UTC
Labels: wontfix
