### ISSUE TITLE
Set environment variables on start?

### ISSUE THREAD

**Issue by basharov** [remy/nodemon#727] opened 2015-11-13 13:23 UTC
I tried this in `nodemon.json`, seems like the command runs but doesn't set the variable:

``` json
  "events":{
    "start":"export PRIVATE_KEY=MyKey"
  }
```

What's the proper way to set an environment variable?

**Comment by remy** [comment] 2015-11-14 16:31
You can, I think, add an env property to your nodemon file, or via the CLI

**Comment by basharov** [comment] 2015-11-16 07:00
This worked, thanks!

```json
{
  "env": {
    "DOCKER_MONGODB": "192.168.99.100:8000"
  }
}
```

**Comment by DoWhileGeek** [comment] 2017-10-16 21:46
If the issue is resolved, lets close it!

**Closed** 2017-12-05 22:54 UTC

**Comment by chovy** [comment] 2018-11-12 09:21
sorry, but what file does this go in?

```
{
  "env": {
    "PRIVATE_KEY": "MyKey",
    "DOCKER_MONGODB": "192.168.99.100:8000"
  }
}
```

**Comment by mrdaliri** [comment] 2018-11-18 15:05
@chovy 

> sorry, but what file does this go in?
> 
> ```
> {
>   "env": {
>     "PRIVATE_KEY": "MyKey",
>     "DOCKER_MONGODB": "192.168.99.100:8000"
>   }
> }
> ```

It the `nodemon.json` file in the root directory.

**Comment by ruipimentel** [comment] 2019-08-22 17:34
> @chovy
> 
> > sorry, but what file does this go in?
> > ```
> > {
> >   "env": {
> >     "PRIVATE_KEY": "MyKey",
> >     "DOCKER_MONGODB": "192.168.99.100:8000"
> >   }
> > }
> > ```
> 
> It the `nodemon.json` file in the root directory.

And also in the [`package.json`, as the value for the `"nodemonConfig"` key](https://github.com/remy/nodemon#packagejson).
