### ISSUE TITLE
Issue on nodemon restart

### ISSUE THREAD

**Issue by ritviksakpal** [remy/nodemon#1873] opened 2021-06-29 22:15 UTC
- nodemon -v: 2.0.8

- node -v: v14.15.4
- Operating system/terminal environment: Windows/hyper terminal
- Command you ran: `nodemon server.js`

### Expected behaviour:

Restart server upon saving the file

### Actual behaviour

get below error:

![image](https://user-images.githubusercontent.com/47916596/123873874-d4774a80-d954-11eb-811e-b292d87b1f08.png)

![image](https://user-images.githubusercontent.com/47916596/123874168-57000a00-d955-11eb-9822-9ab625013cfd.png)

### Steps to reproduce

I've created demo code: -

```
const express = require('express');
const app = express();
app.get("/", function (req, res) {
    res.send("Hello");
})
app.get("/contact", function (req, res) {
    res.send("Contact");
})
app.get("/about", function (req, res) {
    res.send("About");
})
app.listen(80, function () {
    console.log("Server started at 80");
});
```
once saving the file and document is changed, I get the above pop up and error on the terminal
---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

![image](https://user-images.githubusercontent.com/47916596/123874245-79922300-d955-11eb-97e3-7c69a581d4bc.png)
![image](https://user-images.githubusercontent.com/47916596/123874262-80209a80-d955-11eb-813f-2452eed02e88.png)

**Comment by remy** [comment] 2021-06-30 10:24
Duplicate of active issue here: https://github.com/remy/nodemon/issues/1872

**Closed by remy** 2021-06-30 10:24 UTC
