### ISSUE TITLE
Make Nodemon support windows 10

### ISSUE THREAD

**Issue by MilkLegend** [remy/nodemon#1412] opened 2018-08-27 00:04 UTC

**Comment by marcus-sa** [comment] 2018-08-27 12:13
Nodemon does work on Windows 10...
Can you provide a repository so we can try to reproduce the error thats occurring ?

**Comment by sudhir600** [comment] 2018-08-28 10:28
ohh, it doesn't work? i was suppose to install this but found your issues. Please update whenever its ready for window 10.

**Comment by remy** [comment] 2018-08-28 10:52
Nodemon does work on windows.

Closing as the issue contains no details (and required info was removed). Happy to look at any issue that includes some semblance of information as to what the issue is.

**Closed by remy** 2018-08-28 10:52 UTC

**Comment by robertdumitrescu** [comment] 2018-09-15 11:35
It does work on Windows alone, but if you need to dynamically run the app in a docker container via volume, it doesn't work.

**Comment by robertdumitrescu** [comment] 2018-09-15 11:59
It seems that is because Windows doesn't emit anything inside the volume that can be picked up by Inotify in Linux. Maybe @remy you can add a polling mechanism or something? I found this issue on docker: https://github.com/docker/for-win/issues/56 Also, it seems that mocha is the only module in node world that picks up the changes, somehow. Tested forever and node-supervisor, both are having the same behaviour as nodemon.

**Comment by marcus-sa** [comment] 2018-09-15 12:43
Yes it does work in a Docker container, simply pass the `-L` argument

**Comment by robertdumitrescu** [comment] 2018-09-16 22:32
> No. It does work in a Docker container, simply pass the `-L` argument

Oh...right. Thanks. I really want for docker to have proper support for this issue, it consumes tons of memory and is very slow and in general, developers tend to choose other OS's just because of stuff like this. 

PS. Is it way to decrease the polling delay?
