### ISSUE TITLE
3 packages are looking for funding

### ISSUE THREAD

**Issue by NocerGal** [remy/nodemon#2125] opened 2023-07-12 06:41 UTC
- Versions: npm v 9.5.1
- `nodemon -v`: 3.0.1
- Operating system/terminal environment (powershell, gitshell, etc):  visualstudioshell
- Command you ran: npm install -g nodemon

### Expected behaviour
 No error when I install Nodemon. 

### Actual behaviour
3 packages are looking for funding
Current message : 

sudo npm install -g nodemon
Password:

changed 34 packages in 592ms

3 packages are looking for funding
### Steps to reproduce
Install nodemon for new project.

---

**Comment by Ratstail91** [comment] 2023-07-12 08:13
It's a feature, not a bug...

**Comment by insanity54** [comment] 2023-07-13 23:59
Thank you for bringing up the issue regarding the npm module and the warnings about funding. I want to clarify that those warnings are not errors, but rather intentional messages designed to raise awareness about the financial needs of open source projects.

Open source projects, including npm modules, are often developed and maintained by volunteers who generously contribute their time and expertise. While the software itself may be free to use, the ongoing maintenance and development require resources, such as server costs, bug fixing, and implementing new features.

To address these financial needs, [npm introduced the feature](https://dev.to/ruyadorno/npm-6-13-0-7f3) to display funding warnings. These warnings serve as a reminder to users that they have the option to financially support the developers behind the modules they rely on. It's a way to help sustain the open source ecosystem and ensure the longevity of these projects.

However, it's important to note that these warnings are not bugs or errors with the nodemon itself. They are simply meant to provide information and encourage users to consider supporting the project financially if they find value in it.

If you're unable or not interested in providing financial support, you can safely ignore these warnings without any impact on the functionality of nodemon. They won't affect the performance or stability of your application.

If you wish to hide funding warning messages, you can do so by following these instructions https://stackoverflow.com/a/63282233/1004931

I hope this clarifies the situation. Please let me know if you have any further questions or concerns.

**Comment by remy** [comment] 2023-07-21 07:33
As they said, not a bug but an npm feature. Closing.

**Closed by remy** 2023-07-21 07:33 UTC
