### ISSUE TITLE
didn't release the port used

### ISSUE THREAD

**Issue by wpchou** [remy/nodemon#1338] opened 2018-05-08 07:13 UTC
- `nodemon -v`: 1.17.3
- `node -v`: v8.10.0
- Operating system/terminal environment: Ubuntu 18.04
- Command you ran: nodemon then Ctrl-C then nodemon again

### Expected behaviour
nodemon should work again

### Actual behaviour
nodemon didn't release the port it was using, thus it failed to start again.

### Steps to reproduce
as command above

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment] 2018-05-08 07:34
Dupe of #1316 - please provide information to replicate otherwise I'll be closing the issue as I can't replicate

**Closed by remy** 2018-05-08 07:34 UTC
