### ISSUE TITLE
How does Nodemon go with the newest node feature "node --inspect"

### ISSUE THREAD

**Issue by wzup** [remy/nodemon#903] opened 2016-09-08 05:55 UTC
Here is a blog post https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

```
node --inspect index.js
```

Does Nodemon support it already?

**Comment by remy** [comment] 2016-09-09 07:25
Don't know, have you tried it?

**Comment by nrempel** [comment] 2016-09-12 21:06
I can confirm that it works great. After a restart, you will be prompted to reconnect to the debugger.

**Comment by tnguyen14** [comment] 2016-09-14 02:16
@nrempel what is the command that you run to enable the debugger?

**Comment by tnguyen14** [comment] 2016-09-14 03:23
Never mind, I figured it was `nodemon --inspect`. It wasn't working because I was on node 6.2.x

**Comment by tonypee** [comment] 2016-11-05 23:06
doesnt seem to work for me - after the reconnect, i get no logs

**Comment by poltak** [comment] 2016-11-11 06:45
For me it restarts and changes the debugging WS address anytime there's a change detected in the source code. The changing of the address means you have to go back to the nodemon output, get the new address, then go to that in Chrome, which messes up the workflow.

**Comment by maciejsikora** [comment] 2016-11-18 09:49
@poltak I have the same, so every time I change something adress to debug is different, it is very bothersome and for sure development time is much longer.

**Comment by june07** [comment] 2016-12-12 03:57
This fixes the workflow problem. Try this Chrome extension https://chrome.google.com/webstore/detail/nim-node-inspector-manage/gnhhdgbaldcilmgcpfddgdbkhjohddkj

**Comment by jadengore** [comment] 2016-12-18 05:10
@june07 Doesn't it change websockets on each reload? I have to close the tab and then it reopens the proper one... still breaking the workflow for me.

**Comment by june07** [comment] 2016-12-18 05:14
You can configure the extension to manage both opening and closing the
tab/window.  Check the options.

On Dec 17, 2016 9:10 PM, "Edward Bramanti" <notifications@github.com> wrote:

@june07 <https://github.com/june07> Doesn't it change websockets on each
reload? I have to close the tab and then it reopens the proper one... still
breaking the workflow for me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/remy/nodemon/issues/903#issuecomment-267803859>, or mute
the thread

**Comment by jadengore** [comment] 2016-12-18 05:20
@june07 Configuration is on, but it still doesn't seem to be working. It doesn't close the window, just shows the screen below:

<img width="451" alt="screenshot 2016-12-17 21 19 28" src="https://cloud.githubusercontent.com/assets/1921464/21291696/8a492462-c49e-11e6-8324-6f711c83fe4b.png">

I'm not on Node 7, maybe that's it.

**Comment by june07** [comment] 2016-12-18 05:32
If you can yell me what your test environment looks like, Ill try to
duplicate the problem.  Yours is the first report of this issue.  Id like
to help.

**Comment by jadengore** [comment] 2016-12-18 05:33
@june07 I'll move this conversation to an issue on your repo

**Comment by june07** [comment] 2017-03-17 23:23
Fyi, long since been resolved.
https://twitter.com/wesbos/status/839871649738555393

http://june07.com/inspect-broke-my-workflow

**Closed** 2017-12-12 23:10 UTC
Labels: wontfix

**Comment by MartinMuzatko** [comment] 2018-01-04 09:02
When I add `--inspect` to `nodemon`, I don't get any info of a socket opened or how to debug it.

**Comment by MartinMuzatko** [comment] 2018-01-04 09:06
I used to do this: `nodemon --inspect 'LOG_LEVEL=debug node server.js`
I found out, instead I have to do this: `LOG_LEVEL=debug nodemon --inspect server.js`
Not sure if the LOG_LEVEL env is passed down to the node `process.env` though

**Comment by rajatpharmeasy** [comment] 2018-08-23 10:45
How do you do it by code? I tried this but it does not work.
``` nodemon({
          script: 'bin/server.js',
          ext: 'js',
          inspect: '0.0.0.0:9229',
        });
```

**Comment by MadLittleMods** [comment] 2018-08-23 22:34
@rajatpharmeasy You can see an example here, https://gitlab.com/gitlab-org/gitter/webapp/blob/86c6174671b01b1441a02e2dd281893bcc9a6ecc/build-scripts/gulpfile-process.js#L110
