### ISSUE TITLE
Got "No valid versions available for duplexer3" at npm install

### ISSUE THREAD

**Issue by MathRobin** [remy/nodemon#1211] opened 2018-01-06 19:16 UTC
- `nodemon -v`: can't install
- `node -v`: 8.9.3
- Operating system/terminal environment: Ubuntu 17.10
- Command you ran: `npm i nodemon -DE`

### Expected behaviour

Install nodemon 1.14.8 as it's the last version.

### Actual behaviour

```shell
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.0 (node_modules/got/node_modules/timed-out):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/math/.npm/_logs/2018-01-06T19_12_34_555Z-debug.log
```

### Steps to reproduce

`npm i nodemon -DE`

**Comment by remy** [comment] 2018-01-06 20:01
Going to close as dupe of #1210

**Closed by remy** 2018-01-06 20:01 UTC
