### ISSUE TITLE
"watching 0 files" for "username.github.io" directories

### ISSUE THREAD

**Issue by kenhoff** [remy/nodemon#808] opened 2016-03-25 18:39 UTC
Hey there - I'm running into some issues when running nodemon inside of a directory that's used for Github Pages and named something like `username.github.io`. 

Adding the -V flag showed:

```
[nodemon] watching 0 files
```

After a little more experimentation, I think that the problem is the `.git` section of the directory name. [I set up an example repo](https://github.com/kenhoff/nodemon-git-issue) where I test `username.github.io` and `username.gifhub.io`. `username.github.io` watches 0 files, and `username.gifhub.io` watches 1 file.

If possible, I'd like a chance to fix this and submit a pull request (first OSS contribution), but I'm not really sure where to start. Any pointers?

Thanks!

(Here's `nodemon --dump`):

```
--------------
node: v5.3.0
nodemon: 1.9.1
command: /usr/local/bin/node /usr/local/bin/nodemon --dump
cwd: /Users/ken/dev/nodemon-git-issue/username.github.io
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/ken/dev/nodemon-git-issue/username.github.io' },
  required: false,
  dirs: [ '/Users/ken/dev/nodemon-git-issue/username.github.io' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: null,
        exec: 'node',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!.git',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!node_modules' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command: { raw: { executable: 'node', args: [] }, string: 'node' } }
--------------
```

**Comment by karlbateman** [comment] 2016-05-21 13:07
I get the same in my NodeJS projects?

**Comment by kenhoff** [comment] 2016-05-22 16:43
Yo @remy - any pointers on how I could contribute to fix this?

Thanks!

**Comment by karlbateman** [comment] 2016-06-03 10:09
@remy could this be related to #839 I have a public repo to reproduce my issue 💣

**Comment by aldum** [comment] 2016-10-13 12:25
This seems to be breaking on all paths which contain a dot [.] character.

**Comment by Zagonine** [comment] 2017-01-26 11:27
Same problem for me. I had to rename my project folder with no dot in order to make nodemon works.

**Comment by micahbrich** [comment] 2017-02-10 16:06
@aldum finally! I was searching high & low, couldn't figure it out — that was it! renamed to a non-dot folder name & it works 🙌

**Comment by omgimanerd** [comment] 2017-09-22 19:00
This is quite annoying. Is there going to be a fix for this anytime soon?

**Comment by remy** [comment] 2017-09-22 19:01
Did you send a PR? If so I can take a look.

**Comment by omgimanerd** [comment] 2017-09-22 19:59
I could do so. I really like using this package, but a lot of my projects have dots in their folder name. Before I create a fork and send a pull request though, I'd just like to confirm that this behavior is desired by the majority of users and this is the direction you want to take (I'm also very unfamiliar with this codebase). Are there any specifications to this change?

**Closed** 2017-12-12 14:20 UTC
Labels: wontfix
