### ISSUE TITLE
Nodemon is crashing when saving a watched file

### ISSUE THREAD

**Issue by HyperNovaVY** [remy/nodemon#1883] opened 2021-07-07 18:00 UTC
- `nodemon -v`:  2.0.9
- `node -v`: 16.4.2
- Operating system/terminal environment: Windows 10, CMD
- Using Docker? What image: No
- Command you ran: Tried with `nodemon -w file` / `nodemon file` / `nodemon -L file`

### Expected behaviour
When saving a watched file, it should restart the server and everything should be working fine, as expected 

### Actual behaviour
It works fine when I run the nodemon command but when I hit CTRL + S on a file it just crashed, I tried to reinstall node and nodemon, I tried restarting my pc as well, killing al node children processes... but nothing has fixed the issue, and google says nothing about it so it's kinda hard to debug it

This is a complete log of the crash:

```> sockets-express@1.0.0 start
> nodemon -L src/server.js

[nodemon] 2.0.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server.js`
App listening on port  3000
[nodemon] restarting due to changes...
node:child_process:826   
    err = new Error(msg);
          ^

Error: Command failed: wmic process where (ParentProcessId=17000) get ProcessId 2> nul
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at kill (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:337:26)
    at Function.run.kill (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:425:7)     
    at Bus.<anonymous> (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:495:7)       
    at Bus.emit (node:events:406:35)
    at restartBus (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (node:events:394:28)
    at FSWatcher.emitWithAll (C:\Users\user.LAPTOP-4J6G2710\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 10924,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}

```

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

```cwd: C:\Users\user.LAPTOP-4J6G2710\Documents\Programacion\Estudio\sockets-express
OS: win32 x64
--------------
{
  run: false,
  system: {
    cwd: 'C:\\Users\\user.LAPTOP-4J6G2710\\Documents\\Programacion\\Estudio\\sockets-express'
  },
  required: false,
  dirs: [
    'C:\\Users\\user.LAPTOP-4J6G2710\\Documents\\Programacion\\Estudio\\sockets-express'
  ],
  timeout: 1000,
  options: {
    dump: true,
    legacyWatch: true,
    ignore: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**',
      re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
    ],
    watch: [ '*.*', re: /.*\..*/ ],
    monitor: [
      '*.*',
      '!**/.git/**',
      '!**/.nyc_output/**',
      '!**/.sass-cache/**',
      '!**/bower_components/**',
      '!**/coverage/**',
      '!**/node_modules/**'
    ],
    ignoreRoot: [
      '**/.git/**',
      '**/.nyc_output/**',
      '**/.sass-cache/**',
      '**/bower_components/**',
      '**/coverage/**',
      '**/node_modules/**'
    ],
    restartable: 'rs',
    colours: true,
    execMap: { py: 'python', rb: 'ruby', ts: 'ts-node' },
    stdin: true,
    runOnChangeOnly: false,
    verbose: false,
    signal: 'SIGUSR2',
    stdout: true,
    watchOptions: {},
    execOptions: {
      script: 'src/server.js',
      exec: 'node',
      args: [],
      scriptPosition: 0,
      nodeArgs: undefined,
      execArgs: [],
      ext: 'js,mjs,json',
      env: {}
    }
  },
  load: [Function (anonymous)],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command: {
    raw: { executable: 'node', args: [ 'src/server.js' ] },
    string: 'node src/server.js'
  }
}
--------------```

**Comment by remy** [comment] 2021-07-07 18:34
Dupe of #1875. Can you jump on that thread and test with the debug build and report back 👍

**Closed by remy** 2021-07-07 18:34 UTC
