### ISSUE TITLE
nodemon crash: TypeError: Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by LeoAlvarez** [remy/nodemon#606] opened 2015-08-04 15:33 UTC
exception in nodemon killing node
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:234:15)
    at exports.exec (child_process.js:103:18)
    at changeFunction (/usr/local/lib/node_modules/nodemon/lib/monitor/watch.js:93:7)
    at module.exports [as _onTimeout] (/usr/local/lib/node_modules/nodemon/lib/monitor/watch.js:293:5)
    at Timer.listOnTimeout (timers.js:89:15)

(leo):~/devel/pscreener => /usr/local/bin/iojs /usr/local/bin/nodemon app.js --dump
4 Aug 08:31:07 - [nodemon] v1.4.0
4 Aug 08:31:07 - [nodemon] to restart at any time, enter `rs`
4 Aug 08:31:07 - [nodemon] watching: *.*
--------------
node: v2.4.0
nodemon: v1.4.0
command: /usr/local/bin/iojs /usr/local/bin/nodemon app.js --dump
cwd: /Users/leo/devel/pscreener
OS: darwin x64
--------------
{ run: false,
  system:
   { cwd: '/Users/leo/devel/pscreener',
     useFind: true,
     useWatch: false,
     useWatchFile: false },
  required: false,
  dirs: [ '/Users/leo/devel/pscreener' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '.git',
        'node_modules',
        'bower_components',
        '.sass-cache',
        re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     restartable: 'rs',
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions:
      { script: 'app.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js',
        env: {},
        execArgs: [] },
     monitor:
      [ '*.*',
        '!/Users/leo/devel/pscreener/.git/**/*',
        '!/Users/leo/devel/pscreener/node_modules/**/*',
        '!bower_components',
        '!.sass-cache' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  command:
   { raw: { executable: 'node', args: [ 'app.js' ] },
     string: 'node app.js' },
  offset: 0 }
--------------

**Comment by remy** [comment] 2015-08-04 20:38
...someone needs to do a PR that fixes io's support in nodemon :(

**Comment by burabure** [comment] 2015-08-05 17:01
+1, same issue on iojs 2.5 / ubuntu 14.04

**Comment by remy** [comment] 2015-08-31 17:50
iojs issue, dupe of #593 (closing as it's a dupe)

**Closed by remy** 2015-08-31 17:50 UTC
