### ISSUE TITLE
nodemon doesnt detect changes in directories with path containing a space and/or parenthesis

### ISSUE THREAD

**Issue by Baira** [remy/nodemon#961] opened 2017-01-04 16:46 UTC
For learning purposes I created a node app in my dropbox directory which is named "Dropbox (MYNAME)". Unfortunately nodemon couldnt detect any changes in the node app directory. Then I put the app.js directory in "C:/", tried again and nodemon worked perfectly.

**Comment by christianhoward** [comment] 2017-01-23 22:35
I also have this issue developing locally on my mac. My directory path has spaces in it and there is no restarting, but when I move everything to my desktop and change the directory to a path without spaces, everything works fine.

**Comment by dmeehan1968** [comment] 2017-09-20 16:21
My problem too.  If the current or any parent directory contains spaces, nodemon fails to spot file changes for any file its monitoring.

**Comment by dmeehan1968** [comment] 2017-12-05 13:27
Still needs fixing

**Comment by remy** [comment] 2017-12-05 16:59
@dmeehan1968 did you test the latest release? I believe it's fixed in 1.12.2+, specifically this line: https://github.com/remy/nodemon/commit/24a4b84717f1a5b37c0399b0ec8a3b174c30a021#diff-b2048f4188632273753b02bbcc2e31deR59

Am going to close for now (as I believe this issue is duped many times in this repo, and I believe…hope!!!—that it's finally sorted and I've gotten around the chokidar issue).

**Comment by remy** [comment] 2017-12-05 16:59
(of course: I'm happy to re-open if it's still not working on latest).

**Closed by remy** 2017-12-05 16:59 UTC

**Comment by dmeehan1968** [comment] 2017-12-05 17:16
I haven't tested, but the line you highlighted seems to be related to Windows and I was running on MacOS.  Apologies for not mentioning that in my original comment.  I don't see anything else in that PR that's likely to resolve the issue.

**Comment by samhatchett** [comment] 2017-12-08 16:09
Confirmed not working for Mac, version 1.12.5

**Comment by BigFax** [comment] 2017-12-27 14:24
I tried on windows 8.1 pro today 27 dec 2017, not working.
Works directly when i remove the space from directory name containing the project ;)

**Comment by remy** [comment] 2017-12-27 16:34
@bigfax please test with latest nodemon (currently 1.14.3 IIRX)

**Comment by BigFax** [comment] 2017-12-27 17:49
@remy it works with last version 1.14.3.
