### ISSUE TITLE
nodemon crashes on change

### ISSUE THREAD

**Issue by Evilu** [remy/nodemon#1456] opened 2018-11-22 10:56 UTC
- `nodemon -v`: ^1.18.6

- `node -v`: v10.13.0

 Operating system/terminal environment: macOS 10.13.6

- Command you ran:
nodemon start

### Expected behaviour
nodemon restarts on change

### Actual behaviour
[nodemon] restarting due to changes...
/*appDir*/node_modules/nodemon/lib/monitor/run.js:336
        spawn('kill', ['-s', sig, child.pid].concat(kids.map(p => p.PID)))
                                                         ^

TypeError: Cannot read property 'map' of undefined

### Steps to reproduce

---

**Comment by iviaks** [comment] 2018-11-22 11:15
@Evilu 
I have a same problem
It's working on Apollo Server but not working on Express or Hapi.js

**Comment by remy** [comment] 2018-11-22 11:16
Dupe of #1455

**Closed** 2018-11-22 11:16 UTC
